#!/bin/bash

# Functions
function printHelp
{
   printf "\n"
   printf "description: gets the current status for all git projects in current directory\n"
   printf "\nusage: -h [[path | p] path]\n"
   printf "\nArguments:\n"
   printf "'-'h or '--'help                        Print Help (this message) and exit\n"
   printf "\n"
}

# Set default path, then get path, if povided
path=$(pwd) 
while [[ $# > 0 ]]
do
key="$1"

case $key in
  -h)
      printHelp
      exit 1
      ;;
  --help)
      printHelp
      exit 1
      ;;
  *)
    # unknown option
    ;;
esac
shift
done

path="$path/*"

# Loop through all imidiate child directories
for dir in $path ; do
   if [ -d "$dir" ] && [ -x "$dir" ]; then
     # get project
     cd $dir
     project=${PWD##*/}

     # fetch latest from repo
     git fetch > /dev/null 2>&1

     # get any non fatal status
     gitStatus="$(git status 2> /dev/null |grep 'Your branch')"

     # print status if found
     if [[ $gitStatus == *"Your branch"* ]]; then
          printf "Project: $project\n"
       printf "$gitStatus";
       printf "\n\n"
     fi

     # navigate back to reset loop
     cd ..
   fi
done