#!/bin/bash
# Use > 1 to consume two arguments per pass in the loop (e.g. each
# argument has a corresponding value to go with it).
# Use > 0 to consume one or more arguments per pass in the loop (e.g.
# some arguments don't have a corresponding value to go with it such
# as in the --default example).
# note: if this is set to > 0 the /etc/hosts part is not recognized ( may be a bug )
while [[ $# > 0 ]]
do
key="$1"

case $key in
  -a)
    A="$2"
    shift
    ;;
 -b)
   B="DEFAULT"
   ;;
 -c)
   C="$2"
   shift
   ;;

  *)
    # unknown option
    ;;
esac
shift
done

echo A          =       "$A"
echo B          =       "$B"
echo C          =       "$C"

